import { Hackathons } from "@/types/entities";
import { TechOwnersType } from "@/types/techowners";

export const TechOwners: TechOwnersType[] = [
  {
    id: 1,
    name: "Protocol Labs",
    domain: "Software research",
    logo: "/pl-to.webp",
    no_of_upcoming_hackathons: 1,
    description:
      "Protocol Labs drives breakthroughs in computing to push humanity forward. ",
    created_at: "",
    updated_at: "",
    linkedin_url:
      "https://www.linkedin.com/company/protocollabs/posts/?feedView=all",
    facebook_url: "",
    x_url: "https://x.com/protocollabs",
    youtube_url: "https://www.youtube.com/@ProtocolLabs",
    discord_url: "",
    telegram_url: "",
    technologies: [],
    instagram_url: "",
    slack_url: "",
    location: "",
    link: "",
    num_employees: "2",
    tagline: "",
  },
  {
    id: 2,
    name: "Microsoft",
    domain: "Consumer electronics",
    logo: "https://s3-alpha-sig.figma.com/img/6122/aed1/816b236c01c3d4d331079b54361238ad?Expires=1745798400&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=q0nnSoPs6qzjMXhlqVqyHj-jt-yuzSjhYP8cck6p9XZoe-BWoyQqkTfbsMKdKlqF0owFcWczKp705EpNf7-jLw~CmigYPp9YkYusn8iv5lAfpZPotlZ1oE9X1t2WgOj7P4zS0Q0CnwDaqWnRdB1~HBAsHP5p7CceQlmYEY09waiNBIos2yX2RCiWZ4vpP1MeV0LT0eRlvzfcuOpnLUNjkGSiuF0RfYHuVsiC6qXUvqXTg0n5rHlgRxkLARcw01-Tu2NpgVilYHnWY7ebhixC7aJIWo~DoXojLoOGc3SO8XlsusSoi8nE8RD7Ha-LOi7QYDiTGeb5ipFskUGqMn5PVQ__",
    no_of_upcoming_hackathons: 2,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    created_at: "",
    updated_at: "",
    linkedin_url: "",
    facebook_url: "",
    x_url: "",
    youtube_url: "",
    discord_url: "",
    telegram_url: "",
    technologies: [],
    instagram_url: "",
    slack_url: "",
    location: "",
    link: "",
    num_employees: "2",
    tagline: "",
  },
  {
    id: 1,
    name: "Oracle",
    domain: "Software research",
    logo: "https://s3-alpha-sig.figma.com/img/6651/7a0f/c2448d2b8f7eb6af9d787072d0456c16?Expires=1745798400&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=eebG~ujnYGEccYnY~jnJ1uUdbF-ngJyWydM0AJtSv51coNM2pM9J71cNwErc0fIN76kRALB96QGUeC7v1PzuNDCWkf9IMp3sB~y0nJTBmz7YOpNrYoVdGRFpZJwmXqZubO92B0uMc0MZLA-LxkXJiufYS-n5K2ioxApfMgLID6RJmG47Ejc9DGTJjaqWmQd9yb~EUbueSsxOkEliCguQy27Pn0Xf-VjMqMtk-Ke9lhsAbNoYJPP0DzqwuPX~zUk6vCALeJDO-kL-gD1vxxfh5MbZdrgokEI0ESFuZyARskeLjv-U-lMxFM7UYqWHDpqg2nLfgfcEom5ON5B096a9Ew__",
    no_of_upcoming_hackathons: 0,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    created_at: "",
    updated_at: "",
    linkedin_url: "",
    facebook_url: "",
    x_url: "",
    youtube_url: "",
    discord_url: "",
    telegram_url: "",
    technologies: [],
    instagram_url: "",
    slack_url: "",
    location: "",
    link: "",
    num_employees: "2",
    tagline: "",
  },
  {
    id: 3,
    name: "IBM",
    domain: "Software research",
    logo: "https://s3-alpha-sig.figma.com/img/5498/98ef/db3b27e37eeadf59a0f186b3b355816b?Expires=1745798400&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=dudOxKsoFuEvYGa3mcL9jx4gQsQ8~fKINJG31hRtMicsvGgDeLwciSwleYBH7X7pklk~DV7gWNuTb-CPCxTp3r7MGQXu~xj2I-ukQCVdWoyUx35tIw9fFLT-DJXONiWTCCtioxThNCOz-iRhmjtxfcEdVM7runcJJC6Qky8eab9yFU9uxcXUAOfI72NmAP7qwEPNtnDIm3xXYzyvMXX4qS8LR7nnI3Sx7vjYw~qIALwu-bDOmJKY8sv512oDQ6vY9bLG299ugJQ39eSsDdnJTdtNGQ6WfBOzMdVpD~2lUHGkcPQ8wuZNXI7Y96ED8FAE4oU~nA5Ke61rhWloUzLfCw__",
    no_of_upcoming_hackathons: 2,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    created_at: "",
    updated_at: "",
    linkedin_url: "",
    facebook_url: "",
    x_url: "",
    youtube_url: "",
    discord_url: "",
    telegram_url: "",
    technologies: [],
    instagram_url: "",
    slack_url: "",
    location: "",
    link: "",
    num_employees: "2",
    tagline: "",
  },
  {
    id: 4,
    name: "Google",
    domain: "Software research",
    logo: "https://s3-alpha-sig.figma.com/img/3e4c/78ec/db0ab4f7c292828d154c75fbdd7946ed?Expires=1745798400&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=Uw1UKt0xd0toMeN4q4CNBUGrrZkPL8JqL3Lm~WHkxN7~b~CS7VB7iKeScaHBcvsYz8xp3yiPEy~TUjSAa5itUBVvy1jUFjiDSmTwWHGyiyYthOZO-t0X4LaAXkFs2~nMMO4hxG-sc4y4LKYqer99KTKLzHBZlOGIxKJc0T7O9M7Cf2GWLeke~q9uuoGqtb-FI0BBIaJDeqyaJFwihvtKdNs9T4VTfJ-jB9jKLfqPtT6fYYFRVGoVIF03f7GDn5OLennQjG1H8gCr~A~P1HcFvIhpp-dhzi5l4xEm-~jCiffa8V12Dd2~PT7E9TNTO0hOOIx7GFDFuOayKdZ6-0dsqQ__",
    no_of_upcoming_hackathons: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    created_at: "",
    updated_at: "",
    linkedin_url: "",
    facebook_url: "",
    x_url: "",
    youtube_url: "",
    discord_url: "",
    telegram_url: "",
    technologies: [],
    instagram_url: "",
    slack_url: "",
    location: "",
    link: "",
    num_employees: "2",
    tagline: "",
  },
  {
    id: 5,
    name: "Adobe",
    domain: "Software research",
    logo: "https://s3-alpha-sig.figma.com/img/9f39/c112/e656b88a530a8ef235dfbefc9e217ae5?Expires=1745798400&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=XVk9nUx7yFXq6BOMr7UpeX56szb8y8CM6GTjSw22LFpNpAGQw9mqp~fVMTtQJSy0JLmf4bT67m3lLwpXx1y5H1gbnssvcU3we7HnUUpTIKsQr1JRAXIZeTyv-Pck65VVctIJ2GJF05Sd2LDq-WJCyKns0f4XhvTg7MIJBASQn9mRUX0G-rQAZVBadr-iXZCzaPcEndbvTgVEgzZH9950Lkvh5VBV57mBq6rcFiWBVhAoTR6BdqAmi4DmTHS1Su9nUpY08a9dYxLFY9QMPk-wvCP62ek~2okcGuqH6phJCqbtWeyER2xBHRDGVCsrNNq~Jm-1YYfQLotHxzuxV21weQ__",
    no_of_upcoming_hackathons: 0,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    created_at: "",
    updated_at: "",
    linkedin_url: "",
    facebook_url: "",
    x_url: "",
    youtube_url: "",
    discord_url: "",
    telegram_url: "",
    technologies: [],
    instagram_url: "",
    slack_url: "",
    location: "",
    link: "",
    num_employees: "2",
    tagline: "",
  },
  {
    id: 6,
    name: "Cognizant",
    domain: "Software research",
    logo: "https://s3-alpha-sig.figma.com/img/6563/10e0/2738c2f70e2d88068eebdc4086ff957a?Expires=1745798400&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=YI8p8TWfp-dDFQIzhQPIG5xMOnAFfG1PtuyD5UHY6x5H1oarZLYRDlpi6pXF49B2pNsya3bbYJUzdIFfIhjRMyO3-fsZIckCqfi499Dr-uaWExxiqYxb4Us99xhGSu2sNK-dEnh3C9grp7HY5h34DfjRd1q9XEjgzNX~PN68bpZCxwb-UB2scaL30yWz1aae4Jsg3ajwgm9u122S-O1sSIIlvezk5CVwnqUHnaRdnLeDuGv1-9SU62TFPk8urFbtiC4V6FCC0Z6ceP15GsC5KQgKMeGRqTCKHrtM8rSfa9xnt1hl3tMo19VGBinv7nLYGC2ddNY~KHzHoax~MNiS0g__",
    no_of_upcoming_hackathons: 0,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    created_at: "",
    updated_at: "",
    linkedin_url: "",
    facebook_url: "",
    x_url: "",
    youtube_url: "",
    discord_url: "",
    telegram_url: "",
    technologies: [],
    instagram_url: "",
    slack_url: "",
    location: "",
    link: "",
    num_employees: "2",
    tagline: "",
  },
  {
    id: 7,
    name: "Apple",
    domain: "Software research",
    logo: "https://s3-alpha-sig.figma.com/img/471d/2419/383b9cd899f8b448c030af221c7e68d1?Expires=1745798400&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=G2TvBeFvE33UVFo5BSF1wCTu5ewNuAWdrO1sdAMCDURJ80itktiabzJb4YWi0VQClVeeYaKSeA5htl6n3q9WamUt8815v8zrcFCKGILPukqWcpKRkpKrZQDA2nDq4zBzOwGirlW06MLHyRtGU0u-PTvT0yw~hn5RC~J2ECzNlz6q2kNSk27lt3QgH-lyytmnA4itTZD2OcEQFymv7RkW6Y2xVUI1Ke5uRWd41EnV0fyc2Pdk308ZuB4fmXq54Vf4b86FN8ZL~tyyQLN1RMoPXa2NBEd~Bg-WJ~b3yAtchQN-Zwqe40oBK~lLseY-37CK5FMw6ggNVo1QmRLQzc3Kjg__",
    no_of_upcoming_hackathons: 2,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    created_at: "",
    updated_at: "",
    linkedin_url: "",
    facebook_url: "",
    x_url: "",
    youtube_url: "",
    discord_url: "",
    telegram_url: "",
    technologies: [],
    instagram_url: "",
    slack_url: "",
    location: "",
    link: "",
    num_employees: "2",
    tagline: "",
  },
];

export const MockedHackathonData = [
  {
    id: 1,
    name: "PL_Genesis: Modular Worlds Hackathon",
    avatar_url:
      "https://dbaimdvhgbmmxfjaszcp.supabase.co/storage/v1/object/public/hackathon-images/logos/PLLogoBrightGreen.svg",
    banner_url:
      "https://dbaimdvhgbmmxfjaszcp.supabase.co/storage/v1/object/public/hackathon-images/logos/PLHeader.png",
    tags: [
      "Privacy",
      "Cryptography",
      "ZK-Proofs",
      "DeFi",
      "AI",
      "Machine Learning",
      "Data Infrastructure",
    ],
    status: "live",
    deadline_to_join: "2025-07-06",
    application_method: "join",
    sponsors: [
      {
        logo: "https://dbaimdvhgbmmxfjaszcp.supabase.co/storage/v1/object/public/hackathon-images/logos/Sponsor1.png",
        name: "Filecoin Foundation/FIL-B",
      },
      {
        logo: "https://dbaimdvhgbmmxfjaszcp.supabase.co/storage/v1/object/public/hackathon-images/logos/sponsor2.svg",
        name: "Bio.xyz",
      },
      {
        logo: "https://dbaimdvhgbmmxfjaszcp.supabase.co/storage/v1/object/public/hackathon-images/logos/sponsor3.svg",
        name: "Checker Network (Space Meridien)",
      },
      {
        logo: "https://dbaimdvhgbmmxfjaszcp.supabase.co/storage/v1/object/public/hackathon-images/logos/sponsor4.svg",
        name: "Mosaia",
      },
      {
        logo: "https://dbaimdvhgbmmxfjaszcp.supabase.co/storage/v1/object/public/hackathon-images/logos/sponsor5.png",
        name: "Near",
      },
      {
        logo: "https://dbaimdvhgbmmxfjaszcp.supabase.co/storage/v1/object/public/hackathon-images/logos/sponsor6.png",
        name: "Near",
      },
      {
        logo: "https://dbaimdvhgbmmxfjaszcp.supabase.co/storage/v1/object/public/hackathon-images/logos/sponsor7.jpg",
        name: "Near",
      },
    ],
    organizer: {
      logo: "https://dbaimdvhgbmmxfjaszcp.supabase.co/storage/v1/object/public/hackathon-images/logos/pl_logo.webp",
      name: "Protocol Labs",
      created_at: "",
      updated_at: "",
      id: 1,
      description: null,
      discord_url: null,
      domain: null,
      facebook_url: null,
      instagram_url: null,
      link: null,
      linkedin_url: null,
      location: null,
      num_employees: null,
      slack_url: null,
      tagline: null,
      technologies: null,
      telegram_url: null,
      x_url: null,
      youtube_url: null
    },
    application_status: "accepted",
    allow_multiple_teams: true,
    updated_at: "",
    created_at: "",
    end_date: "",
    team_limit: 5,
    technologies: null,
    type: "virtual",
    organizer_id: 3,
    start_date: "",
    subdomain: "",
    deadline_to_submit: "",
    description: "",
    grand_prizes: [],
    location: "",
  },
];


