export const initialSkills = [
  "iOS Development",
  "Android Development",
  "Mobile Application",
  "Web Development",
  "Frontend Development",
  "Backend Development",
  "Fullstack Development",
  "DevOps",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "Data Science",
  "Data Engineering",
  "Data Analytics",
  "Business Intelligence",
  "Cloud Engineering",
  "Cloud Architecture",
  "Product Management",
  "Project Management",
  "UI/UX Design",
  "Cybersecurity",
  "Blockchain",
  "Crypto",
  "Smart Contract Development",
  "Penetration Testing",
  "Site Reliability Engineering",
  "Software Testing",
  "QA Automation",
  "Embedded Systems",
  "Game Development",
  "AR/VR Development",
  "NLP Engineering",
  "MLOps",
  "Bioinformatics",
  "Edge Computing",
  "IoT Development",
  "Technical Writing",
  "Agile Methodologies",
  "Scrum",
  "Solution Architecture",
  "Performance Optimization",
  "System Design",
  "Database Administration",
  "Technical Support",
  "Customer Success",
  "CRM Implementation",
  "E-commerce Development",
  "API Design",
  "Open Source Contribution",
  "Accessibility Engineering",
  "Networking",
];


export const technology = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Go",
  "Ruby",
  "Swift",
  "Kotlin",
  "Dart",
  "PHP",
  "SQL",
  "NoSQL",
  "HTML",
  "CSS",
  "SASS",
  "Less",
  "React",
  "Vue.js",
  "Angular",
  "Next.js",
  "Nuxt.js",
  "Node.js",
  "Express.js",
  "NestJS",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "Laravel",
  "Ruby on Rails",
  "REST",
  "gRPC",
  "Firebase",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "SQLite",
  "Oracle DB",
  "Docker",
  "Kubernetes",
  "Terraform",
  "AWS",
  "Azure",
  "Google Cloud",
  "DigitalOcean",
  "Heroku",
  "Netlify",
  "Vercel",
  "Jenkins",
  "GitHub Actions",
  "CI/CD",
  "Git",
  "Webpack",
  "Vite",
  "Babel",
  "ESLint",
  "Prettier",
  "Figma",
  "Sketch",
  "Framer",
  "Jira",
  "Notion",
  "Postman",
  "Swagger",
  "OpenAI API",
  "Hugging Face",
  "LangChain",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Tableau",
  "Power BI",
  "Matlab",
  "Unity",
  "Unreal Engine",
  "Rust",
  "WASM",
  "Cross-Chain Communication",
  "Smart Contracts",
  "AI/ML Agents",
  "Web3.js",
  "Ethers.js",
  "IPFS / Decentralized Storage",
  "GraphQL",
  "Solidity",
  "Rust",
  "Python",
  "TypeScript",
  "JavaScript",
  "Go",
  "Java",
  "C++",
  "C#",
  "Kotlin",
  "Swift",
  "React",
  "Next.js",
  "Hardhat",
  "Truffle",
  "Foundry",
  "Django",
  "Express",
  "NestJS",
  "Vue",
  "Svelte",
  "Flask",
  "Ethereum",
  "Base",
  "Solana",
  "Polygon",
  "Arbitrum",
  "Optimism",
  "Avalanche",
  "Zora",
  "BNB Chain",
  "Fantom",
  "Near",
  "Near SDK",
  "IPFS",
  "Filecoin",
  "Chainlink",
  "Lit Protocol",
  "Supabase",
  "Alchemy",
  "Infura",
  "The Graph",
  "Moralis",
  "Thirdweb",
  "LangChain",
  "AgentKit",
  "OpenAI",
  "Pinecone",
  "HuggingFace",
  "Replicate",
  "VectorDB",
  "UnstructuredIO",
  "Anthropic",
  "GPT-4",
  "Docker",
  "GitHub Actions",
  "Vercel",
  "Netlify",
  "Terraform",
  "Kubernetes",
  "Railway",
  "Render",
  "Cloudflare",
  "AWS Lambda",
  "MetaMask",
  "WalletConnect",
  "RainbowKit",
  "Coinbase Wallet",
  "Phantom",
  "Trust Wallet",
  "Torus",
  "Safe",
  "Tailwind CSS",
  "Figma",
  "ShadCN",
  "Chakra UI",
  "Material UI",
  "Storybook",
  "Framer Motion",
];

// Add this line after the array definition to remove duplicates
export const initialTechnology = Array.from(new Set(technology));
